### ISSUE TITLE
User handles sometimes show as ellipsis

### ISSUE THREAD

**Issue by karkinetta** [funidata/hybridilusmu#10]
Joidenkin paikallaolijoiden tägi ei näy vaan tilalla näkyy tällainen: @...

Tämä vaikuttaa toistuvan satunnaisesti eli ei ole esim. henkilöstä kiinni. Tilanne korjaantuu listan päivityksellä (Päivitä-painike). Tällöin tulee siis henkilön nimi esille.

**Comment by VoxBorealis** [comment]
Hyvin todennäköisesti juurikin jokin Slackin oma "ominaisuus". Koitin replikoida tätä bugia syöttämällä erilaista dataa home.js:n getRegisterationsBlock():iin, missä nuo renderöidään, mutta en millään saanut tageja näkymään muodossa @....

Suljen issuen toistaiseksi, ellei tämä ongelma ala ilmenemään useammin.
