### ISSUE TITLE
Fix scheduled messages not being updated on newly subscribed jobs

### ISSUE THREAD

**Issue by VoxBorealis** [funidata/hybridilusmu#105]
For some reason the app is not updating/editing the scheduled messages in the Tampere channel **in production**. Locally everything works as intended.

**Comment by VoxBorealis** [comment]
There is a bug in the [scheduleMessage](https://github.com/funidata/hybridilusmu/blob/main/app/src/scheduler/scheduler.js) function. Currently it only saves the job to the database when it has already found any job on the given channel -- this means that newly created jobs are never saved to the database unless you perform the `/tilaa` command twice. 

**TODO:**

- [ ] Fix the code so that jobs are always created/updated **unless** the function is called from the `startScheduling` function, which would mean that we fetch the jobs from the DB and then save them immediately after... 
- [ ] Add console.log when a new Job is saved to the database

**Comment by VoxBorealis** [comment]
It appears that even though the job is saved to the DB, it will not persist through restarts(?)

**Comment by joonashak** [comment]
Not relevant with new implementation (:
