### ISSUE TITLE
Fix app crashing if /tilaa is used in user DMs

### ISSUE THREAD

**Issue by VoxBorealis** [funidata/hybridilusmu#106]
The app will crash if `/tilaa`-command is used in 'user to user' direct messages. It will attempt to send an ephemeral message to the channel (the direct message conversation) but it doesn't have access to it. 

See: [postEphemeralMessage](https://github.com/funidata/hybridilusmu/blob/0f5b7fb3b5ddb2e369718806b0772bc1b4e3f966/app/src/helperFunctions.js#L33) function.

**Comment by joonashak** [comment]
Slash commands will not be used going forward.
