### ISSUE TITLE
Mahdollisuus tilata ajasetettu viesti jossa seuraavan päivän läsnä-ilmoittautuneet

### ISSUE THREAD

**Issue by mikkotee** [funidata/hybridilusmu#111]
Käyttäjänä haluaisin nähdä seuraavan päivän ilmoittautuneet automaattisesti tilattuna tiettynä kellonaikana ja tietylle ryhmälle.

**Comment by joonashak** [comment]
Tulee uuteen tiimi-/toimistonäkymään.
