### ISSUE TITLE
Hybridilusmu yhdistää postgresiin ilman ssl:ää

### ISSUE THREAD

**Issue by IWallg** [funidata/hybridilusmu#112]
Hybridilusmun tietokannan eriyttämisessä omalle instanssiilleen päivittyi tietokannan versio `rds postgres14 -> postgres16`. Tämän myötä rds:n parametrin oletusarvo muuttui `rds.force_ssl = 0 -> 1`

Hybridilumsu epäonnistuu yhdistämään uuteen tietokantaan virheellä 
`ERROR: no pg_hba.conf entry for host "10.37.8.159", user "hybridilusmu", database "hybridilusmu_dev", no encryption`

Pitäisi varmistaa, että Hybridilusmun tietokantayhteys käyttää ssl:ää

**Comment by joonashak** [comment]
Kaiku will resolve this issue in a few weeks (:
