### ISSUE TITLE
Add more statuses

### ISSUE THREAD

**Issue by joonashak** [funidata/hybridilusmu#49]
Add third status to communicate that the user is absent (on vacation, leave, etc.). This issue is probably ready for development but might be worthwhile to hold until we figure out if this should be done in conjunction with other related features.

Other statuses, such as "vacation", could also be added.

**_However, I think we should confer with Toni to make sure this is okay from GDPR etc. point of view._**

**Comment by mikkotee** [comment]
Duplicate https://github.com/funidata/hybridilusmu/issues/8

**Comment by Granigan** [comment]
"Absent", "Poissa" should solve any GDPR-concerns, and would cover sick leaves, vacations, and conferences all alike.

**Comment by joonashak** [comment]
KAIKU-7
