### ISSUE TITLE
Send DM to present people

### ISSUE THREAD

**Issue by darumor** [funidata/hybridilusmu#5]
Slackissa on #toimisto -kanava, mutta siellä jos pingaa @channel tai @here , niin pingi menee kuitenkin kaikille kanavalla olijoille. Olisi kätevää, jos hybridilusmun avulla voisi lähettää viestin kaikille toimistolla olijoille, esim. seuraavissa tapauksissa:
- "avaimet jäi himaan, tarttis päästä sisään"
- "lähetäänkö lounaalle?"
- "voisko joku ottaa vastaan lähetyksen?"
- "karkkia keittiössä"

**Comment by joonashak** [comment]
#6 will effectively implement this.
