### ISSUE TITLE
Status summary to see number of office days etc

### ISSUE THREAD

**Issue by mikkotee** [funidata/hybridilusmu#9]
Etätyössä on työhuonevähennysmahdollisuus mikäli etätyön määritelmä täyttyy työpäivien muodossa. Olisi hyödyllistä saada hybridilusmulta suoraan lista siitä, onko ollut toimistolla vai ei. Toki täytynee miettiä tarkkaan / selvittää onko hybridilusmu riittävä kyseisen tiedon keruuseen, vai pitääkö se tieto tuottaa jotain muuta kautta.

**Comment by joonashak** [comment]
KAIKU-5
